Fix all warnings (#1530)
* Fix int to bool compare warning

warning C4805: '!=': unsafe mix of type 'const int' and type 'bool' in operation

* Fix narrowing conversions

* Fix unused variables

* Fix use of incorrect assert format macro

* Remove min/max macros

Use the Min/Max templated functions from basetypes.h, instead

* Fix MSVC false positive warning

* Fix missing includes

* Fix CMake MSVC EH flags

Don't need to toggle this on x64 since we currently won't throw from that path

* Fix usage of str literal without args

-Wformat-security

* Fix stray token after endif

* GCC: suppress -Wstringop-truncation from SDK base func

Suppress warning for what is apparently intentional behaviour from the
SDK.

gcc steamrt3

* Fix buffer underflow for 0 len inputs

* Fix CMake warning for C code

'-Wno-invalid-offsetof' is valid for C++/ObjC++ but not for C

* Remove redundant casts

* Remove unused helper macro

* fix ub

"output" must be initialized, because in the call to LowLevelByteSwap its
value is evaluated, and as per [basic.indet] 2:

> Except in the following cases, if an indeterminate value is produced
by an evaluation, the behavior is undefined (...)

Also change the "output" type from int to T.

* -Wmaybe-uninitialized

* fix array index overflow

* Exclude compiler opts unused by MSVC

fp:fast, O2, and Oy- for msvc

* Fix MSVC compiler options warning

Oy- is not available for x64

* Simplify MSVC optimization flags

O2 is equivalent to /Og /Oi /Ot /Oy /Ob2 /GF /Gy

* Set initial default branch name

Silence a git warning emitted from actions/checkout

For context:
https://git-scm.com/docs/git-init#Documentation/git-init.txt---initial-branchbranch-name

* Remove redundant ninja install

Resolves build log warning:

2025-12-13T11:50:19.1670599Z Warnings:
2025-12-13T11:50:19.1679122Z  - ninja - ninja v1.13.2 already installed.
2025-12-13T11:50:19.1679513Z  Use --force to reinstall, specify a version to install, or try upgrade.

* Error on missing files for upload-artifact action

* Fix comment url

* Cleanup unused variable

* Treat warnings as errors

* Add "nwae" option

If the branch name or the latest commit message contains the phrase "nwae"
(short for: no-warnings-as-errors), allow CI to skip warnings-as-errors for the build.
This is inteded as means for devs to temporarily dodge the warning rules in exceptional
situations (breakage from compiler version changes etc), but the preferred solution almost
always is to actually fix the warning instead.

* Update documentation

* Unsuppress -Waddress and -Wstrict-aliasing

* Fix incorrect logic in IsKeypad

The SDK path of IsKeypad always returns false because of comparing against an incorrect value. Probably a typo?

* Fix overflow check

Have to check int against INT_... limits instead of LONG_..., because the standard only specifies the *minimum* width of fundamental types. This would break at least for Clang 14 otherwise.

* Fix Clang 14 warning

* Fix warnings compatibility with Clang

* Fix strict aliasing rule violations

* [[maybe_unused]] on members only used for Clang

So we heard you like [[maybe_unused]] so we emitted maybe unused warnings for your maybe unused attributes

* Fix ambiguous whitespace

* Fix Clang ambiguous GCC/MSVC preprocessor defines

Clang may opt to define preprocessor identifiers of other compilers like
GCC and MSVC. This breaks compiler-specific code. Add helper macros to
work around this without needing to ifndef for clang all over the place.

* Fix warning: unused-private-field

* Fix redundant assignment warning

* Fix EHANDLE operator== ambiguity

Declare a non-member overloaded operator== candidate for CHandle<T> to
fix the ISO C++20 ambiguous-reversed-operator warning for cases where lhs
and rhs ordering could be either.

* Fix nullptr indirection

* Suppress thisptr null check warning

Suppress warning for Clang 14:

error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]

Not removing the check, just in case there is some bizarre way in which
non-well-defined SDK code relies on this condition.

* Fix undefined-bool-conversion

* Qualify crash trap as volatile

Mark the debug crash trap as volatile to avoid it being optimized away.

Fix for Clang 14:
error: indirection of non-volatile null pointer will be deleted, not trap [-Werror,-Wnull-dereference]

* Fix operator precedence bug

logical NOT in !lhs==rhs applies to lhs only, but meant to check lhs!=rhs

* Fix tautological ptr compare

* Fix incorrect arguments for BuildWorldRenderLists

* Refactor neo_root_serverbrowser

* Qualify ->~T for nonvirtual CUtlVector<T> cleanup

For CUtlVector<T> container cleanup, qualify all destructor calls for
nonvirtual type T.

Also statically assert that all contained elements of type T either
are final, have a virtual destructor, or are nonpolymorphic, to catch
most cases where the dtor of an inherited object might accidentally
be invoked via a base class ptr (which would be UB).

* fixup: qualify nonvirtual dtor calls

* Fix operator typo

bitwise OR -> logical OR

* Fix incorrect input args

Assuming a random range was intended

* Fix implicit-const-int-float-conversion

* Fix: tautological-undefined-compare

* Fix ambiguous operator==

* Fix warning about implicit float->bool conversion

clang 14 -Wliteral-conversion

* Fix bug with incorrect color rgba input args type

* Fix operator bug with bitflag check

Logical to bitwise AND

* Fix bad ptr compare

* fix self-assign warning

-Wself-assign-field

* Fix bad float->int conversion

* Clean redundant lambda capture

* Fix operator precedence

* Suppress VMT overwrite warning

* Fix literal to nullptr comparison warning

* Fix linker error

* Use crash intrinsics

* Clang 19 warning suppression compat

* Check for nullptr from GetPlayerNetInfo

* Fix threadtools regression

* Nontrivial memcpy

* Use std::swap for V_swap

* Avoid dangling pointer from reference

The memory is technically properly allocated in the reentrant
pReturn->ConvertToCopiedData() call in the vscript binding macros,
but as the reference goes out of scope it could technically blow up.

This change makes g++-14 (SteamRT 14.2.0-19~steamrt3.1+bsrt3.1) 14.2.0
happy for the release build with -Wall

* Fix backslash-newline at end of file

g++-14 (SteamRT 14.2.0-19~steamrt3.1+bsrt3.1) 14.2.0

* suppress array index warning

* Fix uninitialized struct bug

* Fix array mismatched bound

* non-const ref can't bind to bit-field

* Fix unused member vars

* Check getcwd return value for errors

```
error: ignoring return value of ‘char* getcwd(char*, size_t)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  281 |                 _getcwd( szCwd, sizeof( szCwd ) );
```

* Check system call retvals for errors

* Fix SHA1 algorithm compile

* Windows runner image from latest -> 2025

Soft-pin the image name to Windows Server 2025 to avoid breakage if/when the latest tag starts pointing to a newer image.

* Add tests for bit_cast

* Fix CMakeLists compiler options for steamrt3 Clang 11

* Cleanup bit_cast

* Cleanup

* Improve memory pun debug

* Fix type pun size ambiguity

sizeof(unsigned long) is not guaranteed to equal sizeof(int); while this
technically doesn't matter since the punned value is truncated to sizeof
the destination, this would break the sizeof equality assert in our
pun(...) helper func for such a case.

* BasicVector

* Fix bad indentation

* fix bad include order

* Fix Clang 21.1 compatibility

* Update documentation

* Fix type pun

* Improve ctor assertions

* Address review feedback

Use utils.cmake variables for CPU arch