Bots follow you when you press +use on them
Simple snake formation while copying thermoptic and crouch actions.
If more than one bot is following, they will choose a neighbor to follow to reduce collisions.

Tweak leader following logic

- Squadmates only follow teammates in same squad star, and stick to their squad star when their squadmates get changed to different squad stars
- Commander now only collects squadmates, other squad stars will hold their position.
- Added fallback cases for failed pathing returns, e.g. falling back to commander when applicable

Also tweak look repulsion behavior:
- make wall repulsion stronger but less range
- reduce friendly repulsion
- make wall whisker and friendly repulsion ranges convar configurable

Code review feedback pass

Thicker highlight border in neo top hud

Bots retreat to cover when in danger

Bots hide behind healthier teammates

Simplify teammate repulsion calcuation

When teammates were farther than default formation length, they did factor those sightlines.

Draw white border around commanded bot avatars

Highlight commanded bot avatar with white border

Highlight following bots in new top hud

Do not allow bot commands in free for all games

Bot improved fan-out at ghost objective

- increased arrival zone to prevent bots from renavigating on top of ghost
- proximity based player repulsion instead of squad based repulsion before, in order to allow non squad members to adjust fanout next to each other
- recalculate path on commander ping to improve responsiveness of repositioning
- reduced ping cooldown for bot following to make bots more responsive to following

Commander loses teammates on teamkill

Rate limit bot repulsion spread calculation every 100ms

Bots break formation to run away from grenades

Fix Linux-specific redeclaration error

/__w/neo/neo/src/game/server/neo/bot/behavior/neo_bot_seek_and_destroy.cpp:577:15: error: 'sv_neo_bot_cmdr_stop_distance_sq' was declared 'extern' and later 'static' [-fpermissive]
  577 | static ConVar sv_neo_bot_cmdr_stop_distance_sq("sv_neo_bot_cmdr_stop_distance_sq", "5000",
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/neo/neo/src/game/server/neo/bot/behavior/neo_bot_seek_and_destroy.cpp:352:15: note: previous declaration of 'sv_neo_bot_cmdr_stop_distance_sq'

Independent bot pings between squad stars

Highlight squad star player  by color if I am their commander, separately from non-commanded squad star teammates.
Group commanded and non-commanded players in squad star.
Only allow teammates to toggle command state.
Change teammate star when used by a commander in a different squad.
Swap teammate star if they are following but just have a different star.
Have bots of different stars obey different commands from the same commander.

sdfsdf

Disperse bots at destinations

Spreading out behavior that takes into account presence of other bots and obstructed views, based on a spring hysteresis inspired algorithm.

Bots go to commanding player's ping